---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-devops-project-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-devops-project-2
  template:
    metadata:
      labels:
        app: astro-devops-project-2
    spec:
      containers:
        - name: astro-devops-project-2
          image: kaustubm/astro-devops-project-2:latest
          ports:
            - containerPort: 3000 # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: astro-devops-project-2-service
spec:
  selector:
    app: astro-devops-project-2
  ports:
    - protocol: TCP
      port: 80 # Expose port 80
      targetPort: 3000
  type: LoadBalancer
